apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: micro_service_user_service
        imagePullPolicy: Never 
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017"  # MongoDB URI for connection

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 5000       # Service port
      targetPort: 5000 # Container port
      nodePort: 30001  # Specific NodePort (optional, Kubernetes will assign one if omitted)
  type: NodePort
